site_name: Recruiting Website
theme: recruiting_website
plugins:
- recruiting_website_navigation
- recruiting_website_title_remover
- interactive_widgets:
    backend_default_memory_limit_bytes: 201326592
