on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan 88.198.72.202 >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_KEY_DEPLOYMENT }}"
      - name: Deploy recruiting-website
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: ssh root@88.198.72.202 /root/deploy.sh
